# Generated by Django 4.2.24 on 2025-09-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="permissions",
            field=models.JSONField(
                default=list,
                help_text="List of permissions for this API key",
                verbose_name="Permissions",
            ),
        ),
    ]
