# Generated by Django 4.2.24 on 2025-09-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailmessagelog",
            name="failed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Failed at"),
        ),
    ]
