# Generated by Django 4.2.24 on 2025-09-12 16:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="Original filename"),
                ),
                (
                    "filename",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Stored filename"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("document", "Document"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("archive", "Archive"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="File type",
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(max_length=100, verbose_name="MIME type"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(verbose_name="File size (bytes)"),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="File checksum"
                    ),
                ),
                ("storage_path", models.TextField(verbose_name="Storage path")),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Public access"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "tags",
                    models.CharField(blank=True, max_length=500, verbose_name="Tags"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expires at"
                    ),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Download count"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "File Upload",
                "verbose_name_plural": "File Uploads",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_by", "created_at"],
                        name="files_fileu_created_8d42de_idx",
                    ),
                    models.Index(
                        fields=["file_type", "created_at"],
                        name="files_fileu_file_ty_137a9a_idx",
                    ),
                    models.Index(
                        fields=["is_public", "expires_at"],
                        name="files_fileu_is_publ_c182be_idx",
                    ),
                ],
            },
        ),
    ]
